// Code generated by counterfeiter. DO NOT EDIT.
package importerfakes

import (
	"context"
	"sync"

	"github.com/rowanjacobs/terraform-provider-vsphereovf/vsphereovf/importer"
	"github.com/vmware/govmomi/object"
	"github.com/vmware/govmomi/vim25/types"
)

type FakeResourcePool struct {
	ImportVAppStub        func(context.Context, types.BaseImportSpec, *object.Folder, *object.HostSystem) (importer.Lease, error)
	importVAppMutex       sync.RWMutex
	importVAppArgsForCall []struct {
		arg1 context.Context
		arg2 types.BaseImportSpec
		arg3 *object.Folder
		arg4 *object.HostSystem
	}
	importVAppReturns struct {
		result1 importer.Lease
		result2 error
	}
	importVAppReturnsOnCall map[int]struct {
		result1 importer.Lease
		result2 error
	}
	ReferenceStub        func() types.ManagedObjectReference
	referenceMutex       sync.RWMutex
	referenceArgsForCall []struct{}
	referenceReturns     struct {
		result1 types.ManagedObjectReference
	}
	referenceReturnsOnCall map[int]struct {
		result1 types.ManagedObjectReference
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeResourcePool) ImportVApp(arg1 context.Context, arg2 types.BaseImportSpec, arg3 *object.Folder, arg4 *object.HostSystem) (importer.Lease, error) {
	fake.importVAppMutex.Lock()
	ret, specificReturn := fake.importVAppReturnsOnCall[len(fake.importVAppArgsForCall)]
	fake.importVAppArgsForCall = append(fake.importVAppArgsForCall, struct {
		arg1 context.Context
		arg2 types.BaseImportSpec
		arg3 *object.Folder
		arg4 *object.HostSystem
	}{arg1, arg2, arg3, arg4})
	fake.recordInvocation("ImportVApp", []interface{}{arg1, arg2, arg3, arg4})
	fake.importVAppMutex.Unlock()
	if fake.ImportVAppStub != nil {
		return fake.ImportVAppStub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.importVAppReturns.result1, fake.importVAppReturns.result2
}

func (fake *FakeResourcePool) ImportVAppCallCount() int {
	fake.importVAppMutex.RLock()
	defer fake.importVAppMutex.RUnlock()
	return len(fake.importVAppArgsForCall)
}

func (fake *FakeResourcePool) ImportVAppArgsForCall(i int) (context.Context, types.BaseImportSpec, *object.Folder, *object.HostSystem) {
	fake.importVAppMutex.RLock()
	defer fake.importVAppMutex.RUnlock()
	return fake.importVAppArgsForCall[i].arg1, fake.importVAppArgsForCall[i].arg2, fake.importVAppArgsForCall[i].arg3, fake.importVAppArgsForCall[i].arg4
}

func (fake *FakeResourcePool) ImportVAppReturns(result1 importer.Lease, result2 error) {
	fake.ImportVAppStub = nil
	fake.importVAppReturns = struct {
		result1 importer.Lease
		result2 error
	}{result1, result2}
}

func (fake *FakeResourcePool) ImportVAppReturnsOnCall(i int, result1 importer.Lease, result2 error) {
	fake.ImportVAppStub = nil
	if fake.importVAppReturnsOnCall == nil {
		fake.importVAppReturnsOnCall = make(map[int]struct {
			result1 importer.Lease
			result2 error
		})
	}
	fake.importVAppReturnsOnCall[i] = struct {
		result1 importer.Lease
		result2 error
	}{result1, result2}
}

func (fake *FakeResourcePool) Reference() types.ManagedObjectReference {
	fake.referenceMutex.Lock()
	ret, specificReturn := fake.referenceReturnsOnCall[len(fake.referenceArgsForCall)]
	fake.referenceArgsForCall = append(fake.referenceArgsForCall, struct{}{})
	fake.recordInvocation("Reference", []interface{}{})
	fake.referenceMutex.Unlock()
	if fake.ReferenceStub != nil {
		return fake.ReferenceStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.referenceReturns.result1
}

func (fake *FakeResourcePool) ReferenceCallCount() int {
	fake.referenceMutex.RLock()
	defer fake.referenceMutex.RUnlock()
	return len(fake.referenceArgsForCall)
}

func (fake *FakeResourcePool) ReferenceReturns(result1 types.ManagedObjectReference) {
	fake.ReferenceStub = nil
	fake.referenceReturns = struct {
		result1 types.ManagedObjectReference
	}{result1}
}

func (fake *FakeResourcePool) ReferenceReturnsOnCall(i int, result1 types.ManagedObjectReference) {
	fake.ReferenceStub = nil
	if fake.referenceReturnsOnCall == nil {
		fake.referenceReturnsOnCall = make(map[int]struct {
			result1 types.ManagedObjectReference
		})
	}
	fake.referenceReturnsOnCall[i] = struct {
		result1 types.ManagedObjectReference
	}{result1}
}

func (fake *FakeResourcePool) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.importVAppMutex.RLock()
	defer fake.importVAppMutex.RUnlock()
	fake.referenceMutex.RLock()
	defer fake.referenceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeResourcePool) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ importer.ResourcePool = new(FakeResourcePool)
