// Code generated by counterfeiter. DO NOT EDIT.
package importerfakes

import (
	"sync"

	"github.com/rowanjacobs/terraform-provider-vsphereovf/vsphereovf/importer"
	"github.com/vmware/govmomi/nfc"
	"github.com/vmware/govmomi/vim25/types"
)

type FakeLease struct {
	UploadStub        func(nfc.FileItem) error
	uploadMutex       sync.RWMutex
	uploadArgsForCall []struct {
		arg1 nfc.FileItem
	}
	uploadReturns struct {
		result1 error
	}
	uploadReturnsOnCall map[int]struct {
		result1 error
	}
	UploadAllStub        func([]types.OvfFileItem, string) error
	uploadAllMutex       sync.RWMutex
	uploadAllArgsForCall []struct {
		arg1 []types.OvfFileItem
		arg2 string
	}
	uploadAllReturns struct {
		result1 error
	}
	uploadAllReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLease) Upload(arg1 nfc.FileItem) error {
	fake.uploadMutex.Lock()
	ret, specificReturn := fake.uploadReturnsOnCall[len(fake.uploadArgsForCall)]
	fake.uploadArgsForCall = append(fake.uploadArgsForCall, struct {
		arg1 nfc.FileItem
	}{arg1})
	fake.recordInvocation("Upload", []interface{}{arg1})
	fake.uploadMutex.Unlock()
	if fake.UploadStub != nil {
		return fake.UploadStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.uploadReturns.result1
}

func (fake *FakeLease) UploadCallCount() int {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	return len(fake.uploadArgsForCall)
}

func (fake *FakeLease) UploadArgsForCall(i int) nfc.FileItem {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	return fake.uploadArgsForCall[i].arg1
}

func (fake *FakeLease) UploadReturns(result1 error) {
	fake.UploadStub = nil
	fake.uploadReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeLease) UploadReturnsOnCall(i int, result1 error) {
	fake.UploadStub = nil
	if fake.uploadReturnsOnCall == nil {
		fake.uploadReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.uploadReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeLease) UploadAll(arg1 []types.OvfFileItem, arg2 string) error {
	var arg1Copy []types.OvfFileItem
	if arg1 != nil {
		arg1Copy = make([]types.OvfFileItem, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.uploadAllMutex.Lock()
	ret, specificReturn := fake.uploadAllReturnsOnCall[len(fake.uploadAllArgsForCall)]
	fake.uploadAllArgsForCall = append(fake.uploadAllArgsForCall, struct {
		arg1 []types.OvfFileItem
		arg2 string
	}{arg1Copy, arg2})
	fake.recordInvocation("UploadAll", []interface{}{arg1Copy, arg2})
	fake.uploadAllMutex.Unlock()
	if fake.UploadAllStub != nil {
		return fake.UploadAllStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.uploadAllReturns.result1
}

func (fake *FakeLease) UploadAllCallCount() int {
	fake.uploadAllMutex.RLock()
	defer fake.uploadAllMutex.RUnlock()
	return len(fake.uploadAllArgsForCall)
}

func (fake *FakeLease) UploadAllArgsForCall(i int) ([]types.OvfFileItem, string) {
	fake.uploadAllMutex.RLock()
	defer fake.uploadAllMutex.RUnlock()
	return fake.uploadAllArgsForCall[i].arg1, fake.uploadAllArgsForCall[i].arg2
}

func (fake *FakeLease) UploadAllReturns(result1 error) {
	fake.UploadAllStub = nil
	fake.uploadAllReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeLease) UploadAllReturnsOnCall(i int, result1 error) {
	fake.UploadAllStub = nil
	if fake.uploadAllReturnsOnCall == nil {
		fake.uploadAllReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.uploadAllReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeLease) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	fake.uploadAllMutex.RLock()
	defer fake.uploadAllMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeLease) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ importer.Lease = new(FakeLease)
